### ISSUE TITLE
Building the firebase functions takes too long

### ISSUE THREAD

**Issue by themichaelyang** [hacknyu/styx#132]
Takes 2-3 seconds for the build step.

**Comment by stefancherubin** [comment]
How long does the entire process take (from build to finish)? Naturally, I would say build time is dependent on your hardware specs, but maybe there's a larger factor?

**Comment by themichaelyang** [comment]
def not a hardware factor. I wonder if I’m using tsc tool wrong?

**Comment by themichaelyang** [comment]
Gonna mark as a wontfix for now

**Comment by NicholasLYang** [comment]
How are you building rn?

**Comment by themichaelyang** [comment]
`npm run build` in `functions`

Let's table this issue for now b/c I already sent out the email

**Comment by NicholasLYang** [comment]
2-3 seconds is expected. Should it take less time? `tsc` isn't the fastest compiler. If you notice, our compile times went up by a lot after I switched to ts-loader.

**Comment by themichaelyang** [comment]
`wontfix` for now.
