### ISSUE TITLE
Responses to automated emails are lost

### ISSUE THREAD

**Issue by themichaelyang** [hacknyu/styx#133]
this is too late now, but in the future any noreply emails should be obvious

**Comment by themichaelyang** [comment]
Note: we are removing manually scripted emails in favor of Mailchimp, but this still needs to be done for any automated.

**Comment by themichaelyang** [comment]
We can also optionally attach an inbox to the email, which actually might be a better solution.

**Comment by NicholasLYang** [comment]
We can fix this by not having tech send emails.
