### ISSUE TITLE
REFACTOR

### ISSUE THREAD

**Issue by NicholasLYang** [hacknyu/styx#68]
Overall the codebase is pretty good, but we have a few issues we need to fix:

- [x] TypeScript. Oh lord, we totally neglected TypeScript errors. I have a branch going (refactor/typescript-errors), but we really need a solution to styles typings. I'll work on that.

- [ ] Input/Select/SchoolInput all have the same boilerplate attached. We could probably refactor this into a component that takes children input. 

- [x] Modules. We need to break up the code into separate modules. One possible division is form code and core code. 

We should get this done by mid January, so that we can then work on other features, like RSVP, check-in and day of features.

This could be a good opportunity for members who are still learning the tech to get in on the development process, as more experienced members can walk them through the codebase.

**Comment by stefancherubin** [comment]
Tracking: https://github.com/hacknyu/website/pull/88

**Comment by stefancherubin** [comment]
Redux Conversion: https://github.com/hacknyu/website/pull/96 & https://github.com/hacknyu/website/pull/97

**Comment by pierreTklein** [comment]
I would definitely recommend splitting components into different folders based on view, and placing shared components into a `shared` directory!

**Comment by NicholasLYang** [comment]
I just opened a PR for a forms module. However, there was some reasoning behind the monolith. Part of the reason I avoided creating modules was the last project I worked on had some frustrating issues with circular dependencies. Namely, getting the redux state slices to play nice across modules was slightly tricky. So what I decided going forward was to compartmentalize only when necessary.

**Comment by themichaelyang** [comment]
@NicholasLYang has this been resolved? Or Input/Select/SchoolInput are still big? I know that our dir structure is still very messy. I'm in favor of closing this issue and breaking it up into smaller issues.

**Comment by NicholasLYang** [comment]
We're in a decent place rn. We have some modules set up, TypeScript is at full strictness and we're using Formik now. I think we can start migrating the backend to Aletheia
