### ISSUE TITLE
Post Hackathon Statistics

### ISSUE THREAD

**Issue by stefancherubin** [hacknyu/styx#70]
Last year I did all of statistics generation with pivot tables (and looking through so many registration data). While it got the job done, I did all of that manually. Clearly I want to optimize this with some good ol' code. 

I learned D3.js in the fall for the Info-Vis course, so I'm planning on making a component for gathering statistics and making nice looking graphs **(This is something that I can do much later, probably once registration closes).** Are there other JS frameworks that do visualization that I should know about? @themichaelyang @NicholasLYang

**Comment by NicholasLYang** [comment]
D3 is pretty much the only library I know of. The stats stuff we might want to do with firebase functions, mostly cause doing it on the front end seems inefficient. I was considering writing a separate god mode site, probably just tacked onto the existing one but only available to admins

**Comment by stefancherubin** [comment]
Yea, I was concerned about performance if we did it on front end; If it's better to use firebase functions, then we can go that route.

**Comment by NicholasLYang** [comment]
We can also just do an old fashioned node app. Or Go if we're feeling fancy

**Comment by stefancherubin** [comment]
Probably will go with old fashioned node app. Will it be able to make nice looking graphs? I'm sure sponsors (and higher up folks at NYU) would love to see that.

**Comment by themichaelyang** [comment]
@stefancherubin lmk if you end up deciding to make this! Would be a neat feature + blog post. Closing this for now since it's not directly relevant to the app.
